
package com.clase.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Calculadora_ImpService", targetNamespace = "http://ws.clase.com/", wsdlLocation = "http://localhost:8080/WS/Calculadora?wsdl")
public class CalculadoraImpService
    extends Service
{

    private final static URL CALCULADORAIMPSERVICE_WSDL_LOCATION;
    private final static WebServiceException CALCULADORAIMPSERVICE_EXCEPTION;
    private final static QName CALCULADORAIMPSERVICE_QNAME = new QName("http://ws.clase.com/", "Calculadora_ImpService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/WS/Calculadora?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CALCULADORAIMPSERVICE_WSDL_LOCATION = url;
        CALCULADORAIMPSERVICE_EXCEPTION = e;
    }

    public CalculadoraImpService() {
        super(__getWsdlLocation(), CALCULADORAIMPSERVICE_QNAME);
    }

    public CalculadoraImpService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CALCULADORAIMPSERVICE_QNAME, features);
    }

    public CalculadoraImpService(URL wsdlLocation) {
        super(wsdlLocation, CALCULADORAIMPSERVICE_QNAME);
    }

    public CalculadoraImpService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CALCULADORAIMPSERVICE_QNAME, features);
    }

    public CalculadoraImpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CalculadoraImpService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ICalcular
     */
    @WebEndpoint(name = "Calculadora_ImpPort")
    public ICalcular getCalculadoraImpPort() {
        return super.getPort(new QName("http://ws.clase.com/", "Calculadora_ImpPort"), ICalcular.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ICalcular
     */
    @WebEndpoint(name = "Calculadora_ImpPort")
    public ICalcular getCalculadoraImpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.clase.com/", "Calculadora_ImpPort"), ICalcular.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CALCULADORAIMPSERVICE_EXCEPTION!= null) {
            throw CALCULADORAIMPSERVICE_EXCEPTION;
        }
        return CALCULADORAIMPSERVICE_WSDL_LOCATION;
    }

}
